services:
  app:
    build: ./app
    container_name: fastify_app
    ports:
      - "3005:3005"
    network_mode: "host"
    environment:
      PORT: 3005
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb

