services:
  app:
    build: ./app
    container_name: fastify_app
    ports:
      - "3005:3005"
    environment:
      PORT: 3000
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring
      
networks:
  monitoring:
    external: true
