{
 "title": "Express Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1m]))"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code=~\"2..\"}[1m])) / sum(rate(http_request_duration_seconds_count[1m])) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  }
 ]
}